#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-rdkafka
Version  : 4.0.0
Release  : 5
URL      : https://pecl.php.net//get/rdkafka-4.0.0.tgz
Source0  : https://pecl.php.net//get/rdkafka-4.0.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: php-rdkafka-lib = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : pcre2-dev
BuildRequires : pkgconfig(rdkafka)
BuildRequires : util-linux

%description
# PHP Kafka client - php-rdkafka
[![Join the chat at https://gitter.im/arnaud-lb/php-rdkafka](https://badges.gitter.im/arnaud-lb/php-rdkafka.svg)](https://gitter.im/arnaud-lb/php-rdkafka?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%package lib
Summary: lib components for the php-rdkafka package.
Group: Libraries

%description lib
lib components for the php-rdkafka package.


%prep
%setup -q -c -n rdkafka-4.0.0
cd %{_builddir}/rdkafka-4.0.0

%build
## build_prepend content
mv rdkafka-4.0.0/* .
rm -rf rdkafka-4.0.0
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/rdkafka.so
